### ISSUE TITLE
pdf is re-build even if the page hasn't changed

### ISSUE THREAD

**Issue by glassus** [brospars/mkdocs-page-pdf#1]
My website has a lot of different pages, but some of them are static and won't change anymore.
Each time I run `mkdocs serve`, the pdf rendering of those pages is rebuild and it takes a loooong time.
Could it be possible to check the changes in the files, and thus only re-build the pdf of these pages ?

**Comment by brospars** [comment]
Thanks for your first issue @glassus ;)

It's true building pdfs takes a long time and thus we could add options to only build changed files or to disable build on `serve`

I don't have time to look into it at the moment but PR are welcome

**Comment by brospars** [comment]
I just discover the `mkdocs serve --dirtyreload` option (`mkdocs serve --help` and [release not](https://www.mkdocs.org/about/release-notes/#support-for-dirty-builds-990)). 

This works exactly as you would expect but do not rebuild navigation or other pages references. So this is only good for development purposes.
