### ISSUE TITLE
timeout too short on some build

### ISSUE THREAD

**Issue by BugJackBarron** [brospars/mkdocs-page-pdf#2]
Hello !

I needed to change the timeout settings in line 35 by 

`  await self.page.goto('file://' + temp.name, timeout=0)`

because i had a constant issue with timeout being too short for some PDF buildings.

Is it possible to add an option to set proper timeout ?

Thanks for your work

**Comment by brospars** [comment]
Default timeout is set to 30s. If your page isn't loading in that time you probably have an issue with some script/styles/images/fonts not loading properly.

But you are right, I'm adding config parameters to set the `timeout` and `waitUntil` options in the next release.
