### ISSUE TITLE
Thank you and Bravo!

### ISSUE THREAD

**Issue by LunkRat** [brospars/mkdocs-page-pdf#5]
Brilliant project, thank you for your contribution!

I found out about it from https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/issues/89#issuecomment-925929124 because I had the Empty page prepended bug. `pyppeteer` is the way to go!

**Comment by LunkRat** [comment]
Forgot to mention the performance improvement. My total build time went from `5.18` seconds down to `1.33` seconds.

Before, using `pdf-export`:
```
$ mkdocs build
[...]
INFO     -  Documentation built in 5.18 seconds
```

After, using `page-to-pdf`:

```
$ mkdocs build
[...]
INFO     -  Documentation built in 1.33 seconds
```

**Comment by brospars** [comment]
Thanks for you feedback !
