### ISSUE TITLE
Support for embedded images

### ISSUE THREAD

**Issue by robertjchristian** [brospars/mkdocs-page-pdf#6]
Edit - This was corrected by referring to /docs/img as /img.
---------

First of all, **thanks** to the team here.  This is great work!

When I build the pages, I'm not able to embed images.  There is no warning.  They just show unresolved with the PDF.  What do I need to do to make this work?

All the best

 Rob

**Comment by robertjchristian** [comment]
Edit.  Answered my own question.  Mkdocs serve allowed me to use doc folder relative urls for images.  For pdf, it has to be relative to the doc.

Thanks all,

Rob

**Comment by brospars** [comment]
Hello @robertjchristian Can you share your mkdocs config ?
